/*
 Navicat Premium Dump SQL

 Source Server         : LLMHomework
 Source Server Type    : PostgreSQL
 Source Server Version : 180000 (180000)
 Source Host           : localhost:5432
 Source Catalog        : postgres
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 180000 (180000)
 File Encoding         : 65001

 Date: 04/11/2025 16:52:48
*/


-- ----------------------------
-- Table structure for my_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."my_user";
CREATE TABLE "public"."my_user" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "username" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "password" varchar(255) COLLATE "pg_catalog"."default",
  "role" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Primary Key structure for table my_user
-- ----------------------------
ALTER TABLE "public"."my_user" ADD CONSTRAINT "my_user_pkey" PRIMARY KEY ("id");
